In [11]:
import os
import sys
import numpy as np
import pandas as pd
import netCDF4 as nc

In [15]:
precursor_dataset = pd.read_csv('/home/user/workdir/CMAQ_Emulator/main/resources/ctrl/precursor_control_2013.csv', index_col=0)
precursor_dataset.head()

,Unnamed: 0,A_NOX_ALL,A_SO2_ALL,A_VOC_ALL,A_NH3_ALL,A_PM25_ALL,B_NOX_ALL,B_SO2_ALL,B_VOC_ALL,B_NH3_ALL,...,P_NOX_ALL,P_SO2_ALL,P_VOC_ALL,P_NH3_ALL,P_PM25_ALL,Q_NOX_ALL,Q_SO2_ALL,Q_VOC_ALL,Q_NH3_ALL,Q_PM25_ALL
0,1,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,2,0.871163,0.751879,1.241296,1.241296,0.837620,0.869528,0.796421,1.008703,1.008703,...,0.866257,0.940154,1.120186,1.120186,0.902149,0.671272,1.139134,1.024438,1.024438,1.328682
2,3,0.734821,0.934779,0.647231,0.647231,0.982618,1.188854,0.832964,1.000202,1.000202,...,1.278162,1.388087,1.284456,1.284456,1.433464,1.127691,0.764985,0.865993,0.865993,1.294374
3,4,1.234901,0.870514,1.263537,1.263537,0.900073,0.955756,1.146775,0.971038,0.971038,...,0.991836,1.010911,1.163405,1.163405,1.079142,1.140885,1.080571,1.275085,1.275085,0.767802
4,5,0.806340,1.019923,0.734720,0.734720,0.640250,1.090280,0.986776,1.147626,1.147626,...,1.093813,0.945476,0.869924,0.869924,0.953224,1.194511,1.317056,0.770811,0.770811,1.123753

In [16]:
sector_dataset = pd.read_csv('/home/user/workdir/CMAQ_Emulator/main/resources/ctrl/sector_control_2013.csv', index_col=0)
sector_dataset.head()

,A_ALL_POW,A_ALL_IND,A_ALL_MOB,A_ALL_RES,A_NH3_AGR,A_ALL_SLV,A_ALL_OTH,B_ALL_POW,B_ALL_IND,B_ALL_MOB,...,P_NH3_AGR,P_ALL_SLV,P_ALL_OTH,Q_ALL_POW,Q_ALL_IND,Q_ALL_MOB,Q_ALL_RES,Q_NH3_AGR,Q_ALL_SLV,Q_ALL_OTH
1,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,0.514472,0.927851,0.945247,0.692404,1.109061,1.314118,0.721184,0.611804,1.087023,0.949001,...,0.534377,1.445089,1.468231,0.996659,1.394900,0.549501,0.787085,1.343032,1.208780,0.512756
3,1.491511,1.186824,0.617696,0.980489,0.584264,0.633402,1.262937,0.667709,0.727940,1.381620,...,1.111289,0.882215,1.439387,0.983968,0.804134,1.274939,0.507539,1.309304,0.734186,1.060638
4,1.315290,1.020411,1.398561,0.913795,0.511858,1.253180,0.784931,1.427361,0.837764,0.818151,...,0.956353,1.254243,1.386165,1.225236,1.149363,1.188416,0.836505,0.750958,1.294267,1.376669
5,1.335318,0.533092,0.682967,1.105300,0.665543,0.743431,0.568938,0.806974,1.161745,1.149824,...,0.830657,0.636206,0.971299,0.904896,1.426850,1.208611,1.174549,1.117821,0.598213,1.016973

In [21]:
o3_precursor_dataset = pd.read_csv('/home/user/workdir/CMAQ_Emulator/main/resources/ctrl/precursor_control_2013.csv', index_col=0)
filtering_column = o3_precursor_dataset.columns[o3_precursor_dataset.columns.str.contains('NOX|VOC')]
o3_precursor_dataset = o3_precursor_dataset[filtering_column].copy()
o3_precursor_dataset.head()

transformed_data = o3_precursor_dataset[filtering_column].copy()

output_file_path = '/home/user/workdir/CMAQ_Emulator/main/resources/ctrl/precursor_control_2013_o3.csv'
transformed_data.to_csv(output_file_path)